### ISSUE TITLE
bilateralgpu call is wrong in GradFun3

### ISSUE THREAD

**Issue by Selur** [Irrational-Encoding-Wizardry/fvsfunc#9]
calling `clip = core.resize.Bicubic(clip, matrix_in_s="470bg",range_s="limited")` gives me:
```
Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 2832, in vapoursynth._vpy_evaluate
File "src\cython\vapoursynth.pyx", line 2833, in vapoursynth._vpy_evaluate
File "E:\Temp\tempPreviewVapoursynthFile15_04_40_980.vpy", line 38, in 
clip = fvsfunc.GradFun3(src=clip, smode=5)
File "I:\Hybrid\64bit\vsscripts\fvsfunc.py", line 328, in GradFun3
flt_y = smooth_mod(src_16, ref_16, smode, radius, thr, elast, planes2)
File "I:\Hybrid\64bit\vsscripts\fvsfunc.py", line 176, in smooth_mod
return bilateral_gpu(src_16, ref_16, radius, thr, elast, planes)
File "I:\Hybrid\64bit\vsscripts\fvsfunc.py", line 207, in bilateral_gpu
last = core.bilateralgpu.Bilateral(src, sigma_spatial=r / 2, sigma_color=t,
File "src\cython\vapoursynth.pyx", line 2551, in vapoursynth.Function.__call__
vapoursynth.Error: Bilateral: Function does not take argument(s) named planes, kernel_size, borderMode
```

according to https://github.com/WolframRhodium/VapourSynth-BilateralGPU the bilateralgpu uses:
`core.bilateralgpu.Bilateral(clip clip, float[] sigma_spatial=3.0, float[] sigma_color=0.02, int[] radius=0, int device_id=0, int num_streams=4, bool use_shared_memory=True)`
in the script it's called with:
https://github.com/Irrational-Encoding-Wizardry/fvsfunc/blob/2f5b28d5ee5c61e37249bca9b3e10a07f337e785/fvsfunc.py#L207
https://github.com/Irrational-Encoding-Wizardry/fvsfunc/blob/2f5b28d5ee5c61e37249bca9b3e10a07f337e785/fvsfunc.py#L208
-> `, planes=planes, kernel_size=0, borderMode=4` should be removed.

**Comment by ted423** [comment]
line 328
line 176

**Comment by Frechdachs** [comment]
Done.
